---@meta

---@class ABPConstructionYard_C : AConstructionSite
---@field StaticMesh27 UStaticMeshComponent
---@field StaticMesh26 UStaticMeshComponent
---@field StaticMesh25 UStaticMeshComponent
---@field StaticMesh24 UStaticMeshComponent
---@field StaticMesh23 UStaticMeshComponent
---@field StaticMesh22 UStaticMeshComponent
---@field StaticMesh21 UStaticMeshComponent
---@field StaticMesh20 UStaticMeshComponent
---@field StaticMesh18 UStaticMeshComponent
---@field StaticMesh17 UStaticMeshComponent
---@field StaticMesh19 UStaticMeshComponent
---@field StaticMesh12 UStaticMeshComponent
---@field StaticMesh15 UStaticMeshComponent
---@field StaticMesh14 UStaticMeshComponent
---@field StaticMesh13 UStaticMeshComponent
---@field StaticMesh16 UStaticMeshComponent
---@field StaticMesh11 UStaticMeshComponent
---@field Audio UAudioComponent
---@field StaticMesh6 UStaticMeshComponent
---@field StaticMesh8 UStaticMeshComponent
---@field StaticMesh5 UStaticMeshComponent
---@field StaticMesh10 UStaticMeshComponent
---@field StaticMesh9 UStaticMeshComponent
---@field StaticMesh7 UStaticMeshComponent
---@field Decal9 UDecalComponent
---@field Decal8 UDecalComponent
---@field Decal7 UDecalComponent
---@field Decal6 UDecalComponent
---@field Decal5 UDecalComponent
---@field Decal4 UDecalComponent
---@field Decal3 UDecalComponent
---@field Decal2 UDecalComponent
---@field Decal1 UDecalComponent
---@field Decal UDecalComponent
---@field Gravel5 UDecalComponent
---@field Gravel4 UDecalComponent
---@field Gravel3 UDecalComponent
---@field Gravel2 UDecalComponent
---@field Gravel1 UDecalComponent
---@field Puddle2 UDecalComponent
---@field Puddle1 UDecalComponent
---@field TownStaircase03 UStaticMeshComponent
---@field StaticMesh4 UStaticMeshComponent
---@field StaticMesh3 UStaticMeshComponent
---@field StaticMesh2 UStaticMeshComponent
---@field StaticMesh1 UStaticMeshComponent
---@field MultiplexedStaticMesh UMultiplexedStaticMeshComponent
---@field StaticMesh UStaticMeshComponent
ABPConstructionYard_C = {}



