---@meta

---@class ABPFortBaseT3_C : AConcreteFortForwardBase
---@field UnderModSlot UBPFortUnderModSlot_C
---@field SpawnPoint15 USpawnPointComponent
---@field SpawnPoint14 USpawnPointComponent
---@field SpawnPoint13 USpawnPointComponent
---@field SpawnPoint12 USpawnPointComponent
---@field SpawnPoint11 USpawnPointComponent
---@field SpawnPoint10 USpawnPointComponent
---@field SpawnPoint9 USpawnPointComponent
---@field SpawnPoint USpawnPointComponent
---@field WaterStencil UBPWaterStencilComponent_C
---@field MultiplexedStaticMesh UMultiplexedStaticMeshComponent
---@field BlockBuildSiteMovement UBoxComponent
---@field LandscapeHoleFront UBoxComponent
---@field FloorDoor UStaticMeshComponent
---@field SideFrontStatic UStaticMeshComponent
---@field SideLeftStatic UStaticMeshComponent
---@field SideBackStatic UStaticMeshComponent
---@field CornerBackRight UStaticMeshComponent
---@field SideBack UStaticMeshComponent
---@field SideLeft UStaticMeshComponent
---@field SideFront UStaticMeshComponent
---@field DirtCornerBackRight UStaticMeshComponent
---@field CornerFrontLeft UStaticMeshComponent
---@field DirtFront UStaticMeshComponent
---@field DirtCornerFrontRight UStaticMeshComponent
---@field DirtCornerFrontLeft UStaticMeshComponent
---@field DirtCornerBackLeft UStaticMeshComponent
---@field CornerBackLeft UStaticMeshComponent
---@field DirtBack UStaticMeshComponent
---@field DirtLeft UStaticMeshComponent
---@field CornerFrontRight UStaticMeshComponent
---@field Decal2 UDecalComponent
---@field Decal1 UDecalComponent
---@field Decal3 UDecalComponent
---@field Roof UStaticMeshComponent
---@field BackWallSocket UBuildSocketComponent
---@field FrontWallSocket UBuildSocketComponent
---@field FrontSocket UBuildSocketComponent
---@field BackSocket UBuildSocketComponent
---@field LeftSocket UBuildSocketComponent
---@field Floor UStaticMeshComponent
---@field LandscapeHole UBoxComponent
---@field BoatHull UBoatHullComponent
---@field ViewTargetCamera UCameraComponent
ABPFortBaseT3_C = {}



