---@meta

---@class ARVMainRoom_C : ABuildableStructure
---@field UberGraphFrame FPointerToUberGraphFrame
---@field Box1 UBoxComponent
---@field StaticMesh21 UStaticMeshComponent
---@field HangedManFlag UStaticMeshComponent
---@field HangManMetal UStaticMeshComponent
---@field Box UBoxComponent
---@field StaticMesh20 UStaticMeshComponent
---@field PointLight1 UPointLightComponent
---@field StaticMesh19 UStaticMeshComponent
---@field ParticleSystem5 UParticleSystemComponent
---@field ParticleSystem4 UParticleSystemComponent
---@field ParticleSystem3 UParticleSystemComponent
---@field ParticleSystem2 UParticleSystemComponent
---@field StaticMesh18 UStaticMeshComponent
---@field StaticMesh17 UStaticMeshComponent
---@field StaticMesh14 UStaticMeshComponent
---@field ParticleSystem1 UParticleSystemComponent
---@field ParticleSystem UParticleSystemComponent
---@field Decal8 UDecalComponent
---@field Decal7 UDecalComponent
---@field Decal6 UDecalComponent
---@field Decal5 UDecalComponent
---@field Decal4 UDecalComponent
---@field Decal3 UDecalComponent
---@field Decal2 UDecalComponent
---@field Decal1 UDecalComponent
---@field Decal UDecalComponent
---@field StaticMesh13 UStaticMeshComponent
---@field StaticMesh12 UStaticMeshComponent
---@field StaticMesh11 UStaticMeshComponent
---@field StaticMesh10 UStaticMeshComponent
---@field StaticMesh9 UStaticMeshComponent
---@field StaticMesh8 UStaticMeshComponent
---@field StaticMesh7 UStaticMeshComponent
---@field StaticMesh6 UStaticMeshComponent
---@field StaticMesh5 UStaticMeshComponent
---@field StaticMesh4 UStaticMeshComponent
---@field StaticMesh3 UStaticMeshComponent
---@field StaticMesh2 UStaticMeshComponent
---@field BasicCrates04 UStaticMeshComponent
---@field HomeRegionCrates02 UStaticMeshComponent
---@field SK_RelicTruck USkeletalMeshComponent
---@field StaticMesh1 UStaticMeshComponent
---@field StaticMesh UStaticMeshComponent
---@field CamouflageCrates01 UStaticMeshComponent
---@field BPStructureInteriorArea UBPStructureInteriorArea_C
---@field BPStructureInteriorArea1 UBPStructureInteriorArea_C
---@field StaticMesh16 UStaticMeshComponent
---@field StaticMesh15 UStaticMeshComponent
---@field StaticMesh14_0 UStaticMeshComponent
---@field StaticMesh13_0 UStaticMeshComponent
---@field StaticMesh12_0 UStaticMeshComponent
---@field StaticMesh8_0 UStaticMeshComponent
---@field StaticMesh11_0 UStaticMeshComponent
---@field StaticMesh10_0 UStaticMeshComponent
---@field StaticMesh9_0 UStaticMeshComponent
---@field StaticMesh1_0 UStaticMeshComponent
---@field StaticMesh7_0 UStaticMeshComponent
---@field StaticMesh6_0 UStaticMeshComponent
---@field StaticMesh5_0 UStaticMeshComponent
---@field StaticMesh4_0 UStaticMeshComponent
---@field StaticMesh3_0 UStaticMeshComponent
---@field StaticMesh2_0 UStaticMeshComponent
---@field StaticMesh_0 UStaticMeshComponent
---@field Roof UStaticMeshComponent
---@field TownWMedS1 UStaticMeshComponent
---@field Timeline_0_Intensity_FF49C7B244E0D069117E96B10CA77D84 float
---@field Timeline_0__Direction_FF49C7B244E0D069117E96B10CA77D84 ETimelineDirection::Type
---@field Timeline_0 UTimelineComponent
ARVMainRoom_C = {}

function ARVMainRoom_C:Timeline_0__FinishedFunc() end
function ARVMainRoom_C:Timeline_0__UpdateFunc() end
function ARVMainRoom_C:ReceiveBeginPlay() end
---@param EntryPoint int32
function ARVMainRoom_C:ExecuteUbergraph_RVMainRoom(EntryPoint) end


