---@meta

---@class ATownWMedAttachedG1_C : AGarrisonHouse
---@field StaticMesh UStaticMeshComponent
---@field TownStaircase03 UStaticMeshComponent
---@field Decal1 UDecalComponent
---@field AITurretMarker01 UDecalComponent
---@field Cabinet2 UStaticMeshComponent
---@field StaticMesh7 UStaticMeshComponent
---@field Cabinet6 UStaticMeshComponent
---@field TownStaircase02 UStaticMeshComponent
---@field AITurretMarker00 UDecalComponent
---@field window04 UStaticMeshComponent
---@field window01 UStaticMeshComponent
---@field PropsCollison04 UBoxComponent
---@field PropsCollison02 UBoxComponent
---@field PropsCollison01 UBoxComponent
---@field Lamp02 UStaticMeshComponent
---@field Lamp01 UStaticMeshComponent
---@field StaticMesh30 UStaticMeshComponent
---@field StaticMesh27 UStaticMeshComponent
---@field StaticMesh26 UStaticMeshComponent
---@field StaticMesh25 UStaticMeshComponent
---@field StaticMesh24 UStaticMeshComponent
---@field StaticMesh22 UStaticMeshComponent
---@field StaticMesh18 UStaticMeshComponent
---@field StaticMesh16 UStaticMeshComponent
---@field Decal3 UDecalComponent
---@field Decal2 UDecalComponent
---@field StaticMesh13 UStaticMeshComponent
---@field StaticMesh12 UStaticMeshComponent
---@field StaticMesh6 UStaticMeshComponent
---@field StaticMesh5 UStaticMeshComponent
---@field StaticMesh4 UStaticMeshComponent
---@field StaticMesh3 UStaticMeshComponent
---@field Decal UDecalComponent
---@field StaticMesh2 UStaticMeshComponent
---@field StaticMesh1 UStaticMeshComponent
---@field StaticMeshProps UBoxComponent
---@field BPStructureInteriorArea UBPStructureInteriorArea_C
---@field BPAIGarrisonTurret3 UBPAIGarrisonTurret_C
---@field BPAIGarrisonTurret UBPAIGarrisonTurret_C
---@field ParticleSystem4 UParticleSystemComponent
---@field ParticleSystem1 UParticleSystemComponent
---@field MultiplexedRoof UMultiplexedStaticMeshComponent
---@field MultiplexedHouse UMultiplexedStaticMeshComponent
---@field Roof UStaticMeshComponent
---@field HouseMesh UStaticMeshComponent
ATownWMedAttachedG1_C = {}



