---@meta

---@class ATownWMedAttachedG2_C : AGarrisonHouse
---@field StaticMesh8 UStaticMeshComponent
---@field StaticMesh7 UStaticMeshComponent
---@field StaticMesh6 UStaticMeshComponent
---@field AITurretMarker01 UDecalComponent
---@field AITurretMarker00 UDecalComponent
---@field PropsCollison04 UBoxComponent
---@field TownStaircase01 UStaticMeshComponent
---@field ShopSign6 UStaticMeshComponent
---@field StaticMesh4 UStaticMeshComponent
---@field Cabinet1 UStaticMeshComponent
---@field Cabinet5 UStaticMeshComponent
---@field StaticMesh5 UStaticMeshComponent
---@field StaticMesh3 UStaticMeshComponent
---@field window02 UStaticMeshComponent
---@field window01 UStaticMeshComponent
---@field BPAIGarrisonTurret3 UBPAIGarrisonTurret_C
---@field BPAIGarrisonTurret UBPAIGarrisonTurret_C
---@field PropsCollison01 UBoxComponent
---@field PropsCollison03 UBoxComponent
---@field PropsCollison02 UBoxComponent
---@field Lamp03 UStaticMeshComponent
---@field Lamp02 UStaticMeshComponent
---@field Lamp01 UStaticMeshComponent
---@field PropagandaPosterWarV9 UStaticMeshComponent
---@field StaticMesh16 UStaticMeshComponent
---@field StaticMesh42 UStaticMeshComponent
---@field StaticMesh39 UStaticMeshComponent
---@field StaticMesh38 UStaticMeshComponent
---@field StaticMesh37 UStaticMeshComponent
---@field StaticMesh36 UStaticMeshComponent
---@field StaticMesh35 UStaticMeshComponent
---@field StaticMesh34 UStaticMeshComponent
---@field StaticMesh33 UStaticMeshComponent
---@field StaticMesh32 UStaticMeshComponent
---@field StaticMesh30 UStaticMeshComponent
---@field StaticMesh29 UStaticMeshComponent
---@field StaticMesh28 UStaticMeshComponent
---@field StaticMesh27 UStaticMeshComponent
---@field StaticMesh26 UStaticMeshComponent
---@field StaticMesh25 UStaticMeshComponent
---@field StaticMesh24 UStaticMeshComponent
---@field StaticMesh23 UStaticMeshComponent
---@field Decal1 UDecalComponent
---@field StaticMesh18 UStaticMeshComponent
---@field StaticMesh17 UStaticMeshComponent
---@field StaticMesh15 UStaticMeshComponent
---@field StaticMesh14 UStaticMeshComponent
---@field StaticMesh11 UStaticMeshComponent
---@field StaticMesh10 UStaticMeshComponent
---@field StaticMesh9 UStaticMeshComponent
---@field Decal UDecalComponent
---@field StaticMesh2 UStaticMeshComponent
---@field StaticMesh1 UStaticMeshComponent
---@field StaticMesh UStaticMeshComponent
---@field StaticMeshProps UBoxComponent
---@field BPStructureInteriorArea1 UBPStructureInteriorArea_C
---@field BPStructureInteriorArea UBPStructureInteriorArea_C
---@field ParticleSystem5 UParticleSystemComponent
---@field ParticleSystem4 UParticleSystemComponent
---@field ParticleSystem1 UParticleSystemComponent
---@field MultiplexedRoof UMultiplexedStaticMeshComponent
---@field MultiplexedHouse UMultiplexedStaticMeshComponent
---@field Roof UStaticMeshComponent
---@field HouseMesh UStaticMeshComponent
local ATownWMedAttachedG2_C = {}



