---@meta

---@class ATownCMedGarrisonG1_C : AGarrisonHouse
---@field Decal38 UDecalComponent
---@field Decal37 UDecalComponent
---@field Decal36 UDecalComponent
---@field Decal35 UDecalComponent
---@field Decal34 UDecalComponent
---@field Decal33 UDecalComponent
---@field Decal32 UDecalComponent
---@field Decal31 UDecalComponent
---@field Decal30 UDecalComponent
---@field StaticMesh4 UStaticMeshComponent
---@field Decal29 UDecalComponent
---@field Decal28 UDecalComponent
---@field Decal27 UDecalComponent
---@field Decal26 UDecalComponent
---@field Decal25 UDecalComponent
---@field Decal24 UDecalComponent
---@field Decal23 UDecalComponent
---@field Decal22 UDecalComponent
---@field Decal21 UDecalComponent
---@field Decal20 UDecalComponent
---@field PropagandaPosterColV4 UStaticMeshComponent
---@field PropagandaPosterColV3 UStaticMeshComponent
---@field PropagandaPosterColV2 UStaticMeshComponent
---@field StaticMesh3 UStaticMeshComponent
---@field StaticMesh2 UStaticMeshComponent
---@field StaticMesh1 UStaticMeshComponent
---@field StaticMesh UStaticMeshComponent
---@field Decal18 UDecalComponent
---@field Decal17 UDecalComponent
---@field Decal14 UDecalComponent
---@field Decal16 UDecalComponent
---@field Decal15 UDecalComponent
---@field Decal13 UDecalComponent
---@field Decal12 UDecalComponent
---@field Decal11 UDecalComponent
---@field Decal10 UDecalComponent
---@field Decal9 UDecalComponent
---@field Decal8 UDecalComponent
---@field Decal7 UDecalComponent
---@field Decal6 UDecalComponent
---@field Decal5 UDecalComponent
---@field Decal UDecalComponent
---@field Window4 UStaticMeshComponent
---@field Decal4 UDecalComponent
---@field BPAIGarrisonTurret_Back UBPAIGarrisonTurret_C
---@field Window3 UStaticMeshComponent
---@field Decal3 UDecalComponent
---@field BPAIGarrisonTurret_Right UBPAIGarrisonTurret_C
---@field Window2 UStaticMeshComponent
---@field Decal2 UDecalComponent
---@field BPAIGarrisonTurret_Front UBPAIGarrisonTurret_C
---@field Window1 UStaticMeshComponent
---@field Decal1 UDecalComponent
---@field BPAIGarrisonTurret_Left UBPAIGarrisonTurret_C
---@field MultiplexedRoof UMultiplexedStaticMeshComponent
---@field MultiplexedHouse UMultiplexedStaticMeshComponent
---@field BPStructureInteriorArea UBPStructureInteriorArea_C
---@field Roof UStaticMeshComponent
---@field HouseMesh UStaticMeshComponent
ATownCMedGarrisonG1_C = {}



