---@meta

---@class AUniqueWWarehouseG2Destroyed_C : ADestroyedGarrisonStation
---@field PillarCollision02 UBoxComponent
---@field PillarCollision01 UBoxComponent
---@field StaticMesh44 UStaticMeshComponent
---@field StaticMesh43 UStaticMeshComponent
---@field StaticMesh42 UStaticMeshComponent
---@field StaticMesh41 UStaticMeshComponent
---@field StaticMesh40 UStaticMeshComponent
---@field StaticMesh39 UStaticMeshComponent
---@field StaticMesh38 UStaticMeshComponent
---@field GarrisonStationRadioStationStaticSwap UBoxComponent
---@field StaticMesh37 UStaticMeshComponent
---@field StaticMesh36 UStaticMeshComponent
---@field GarrisonStationOperatingPostStaticSwap UBoxComponent
---@field StaticMesh35 UStaticMeshComponent
---@field StaticMesh34 UStaticMeshComponent
---@field StaticMesh33 UStaticMeshComponent
---@field StaticMesh32 UStaticMeshComponent
---@field StaticMesh31 UStaticMeshComponent
---@field StaticMesh30 UStaticMeshComponent
---@field StaticMesh29 UStaticMeshComponent
---@field StaticMesh28 UStaticMeshComponent
---@field StaticMesh27 UStaticMeshComponent
---@field StaticMesh26 UStaticMeshComponent
---@field StaticMesh25 UStaticMeshComponent
---@field StaticMesh6 UStaticMeshComponent
---@field ArtilleryShelterMeshStaticSwap UBoxComponent
---@field StaticMesh24 UStaticMeshComponent
---@field StaticMesh23 UStaticMeshComponent
---@field StaticMesh22 UStaticMeshComponent
---@field StaticMesh21 UStaticMeshComponent
---@field StaticMesh20 UStaticMeshComponent
---@field StaticMesh19 UStaticMeshComponent
---@field Decal7 UDecalComponent
---@field StaticMesh18 UStaticMeshComponent
---@field StaticMesh17 UStaticMeshComponent
---@field StaticMesh16 UStaticMeshComponent
---@field Decal6 UDecalComponent
---@field StaticMesh15 UStaticMeshComponent
---@field StaticMesh14 UStaticMeshComponent
---@field StaticMesh13 UStaticMeshComponent
---@field StaticMesh12 UStaticMeshComponent
---@field StaticMesh11 UStaticMeshComponent
---@field StaticMesh10 UStaticMeshComponent
---@field Decal5 UDecalComponent
---@field Decal4 UDecalComponent
---@field StaticMesh9 UStaticMeshComponent
---@field StaticMesh8 UStaticMeshComponent
---@field StaticMesh7 UStaticMeshComponent
---@field StaticMesh5 UStaticMeshComponent
---@field StaticMesh4 UStaticMeshComponent
---@field StaticMesh3 UStaticMeshComponent
---@field ParticleSystem1 UParticleSystemComponent
---@field StaticMesh2 UStaticMeshComponent
---@field Decal3 UDecalComponent
---@field Decal2 UDecalComponent
---@field ParticleSystem UParticleSystemComponent
---@field StaticMesh1 UStaticMeshComponent
---@field StaticMesh UStaticMeshComponent
---@field StaticProps UBoxComponent
---@field Decal UDecalComponent
---@field Decal1 UDecalComponent
---@field BPStructureInteriorArea UBPStructureInteriorArea_C
---@field Roof UStaticMeshComponent
---@field HouseMesh UStaticMeshComponent
local AUniqueWWarehouseG2Destroyed_C = {}



