---@meta

---@class AUniqueWPubG1Destroyed_C : ADestroyedGarrisonHouse
---@field Cabinet4 UStaticMeshComponent
---@field StaticMesh29 UStaticMeshComponent
---@field StaticMesh28 UStaticMeshComponent
---@field StaticMesh27 UStaticMeshComponent
---@field RuinedMesh9 URuinedMeshComponent
---@field RuinedMesh8 URuinedMeshComponent
---@field RuinedMesh7 URuinedMeshComponent
---@field RuinedMesh6 URuinedMeshComponent
---@field RuinedMesh5 URuinedMeshComponent
---@field RuinedMesh4 URuinedMeshComponent
---@field RuinedMesh3 URuinedMeshComponent
---@field RuinedMesh2 URuinedMeshComponent
---@field RuinedMesh1 URuinedMeshComponent
---@field UniqueWPubG1Ruin UStaticMeshComponent
---@field StaticMeshCollision04 UBoxComponent
---@field StaticMesh26 UStaticMeshComponent
---@field StaticMesh25 UStaticMeshComponent
---@field StaticMesh24 UStaticMeshComponent
---@field StaticMesh23 UStaticMeshComponent
---@field StaticMesh22 UStaticMeshComponent
---@field StaticMeshCollision03 UBoxComponent
---@field StaticMeshCollision02 UBoxComponent
---@field StaticMesh21 UStaticMeshComponent
---@field WoodBarrel_01 UStaticMeshComponent
---@field StaticMesh1 UStaticMeshComponent
---@field Rug09 UStaticMeshComponent
---@field PhotoFrame1 UStaticMeshComponent
---@field StaticMesh UStaticMeshComponent
---@field Cabinet3 UStaticMeshComponent
---@field CoverHalfBath1d UStaticMeshComponent
---@field StaticMesh2 UStaticMeshComponent
---@field Decal4 UDecalComponent
---@field Decal3 UDecalComponent
---@field Decal2 UDecalComponent
---@field Decal1 UDecalComponent
---@field Decal UDecalComponent
---@field TownRubbleCornerIn01 UStaticMeshComponent
---@field StaticMesh19 UStaticMeshComponent
---@field StaticMesh18 UStaticMeshComponent
---@field StaticMesh17 UStaticMeshComponent
---@field StaticMesh16 UStaticMeshComponent
---@field StaticMesh15 UStaticMeshComponent
---@field StaticMesh14 UStaticMeshComponent
---@field StaticMesh13 UStaticMeshComponent
---@field StaticMesh12 UStaticMeshComponent
---@field StaticMesh20 UStaticMeshComponent
---@field StaticMesh10 UStaticMeshComponent
---@field StaticMesh9 UStaticMeshComponent
---@field StaticMesh8 UStaticMeshComponent
---@field StaticMesh7 UStaticMeshComponent
---@field StaticMesh6 UStaticMeshComponent
---@field StaticMesh5 UStaticMeshComponent
---@field StaticMesh4 UStaticMeshComponent
---@field StaticMesh3 UStaticMeshComponent
---@field StaticMesh11 UStaticMeshComponent
---@field StaticProps UBoxComponent
---@field StaticMeshCollision01 UBoxComponent
---@field BPStructureInteriorArea1 UBPStructureInteriorArea_C
---@field BPStructureInteriorArea UBPStructureInteriorArea_C
---@field Roof UStaticMeshComponent
---@field HouseMesh UStaticMeshComponent
AUniqueWPubG1Destroyed_C = {}



