---@meta

---@class AVillageWMedAttachedG2_C : AGarrisonHouse
---@field Lamp UParticleSystemComponent
---@field StaticMesh21 UStaticMeshComponent
---@field StaticMesh20 UStaticMeshComponent
---@field StaticMesh19 UStaticMeshComponent
---@field StaticMesh17 UStaticMeshComponent
---@field StaticMesh15 UStaticMeshComponent
---@field PropsCollison06 UBoxComponent
---@field Decal3 UDecalComponent
---@field StaticMesh14 UStaticMeshComponent
---@field StaticMesh12 UStaticMeshComponent
---@field StaticMesh11 UStaticMeshComponent
---@field StaticMesh10 UStaticMeshComponent
---@field StaticMesh9 UStaticMeshComponent
---@field StaticMesh8 UStaticMeshComponent
---@field StaticMesh7 UStaticMeshComponent
---@field StaticMesh5 UStaticMeshComponent
---@field BPStructureInteriorArea1 UBPStructureInteriorArea_C
---@field StaticMesh4 UStaticMeshComponent
---@field StaticMesh2 UStaticMeshComponent
---@field PropsCollison05 UBoxComponent
---@field StaticMesh UStaticMeshComponent
---@field AITurretMarker03 UDecalComponent
---@field window02 UStaticMeshComponent
---@field BPAIGarrisonTurret1 UBPAIGarrisonTurret_C
---@field PropsCollison03 UBoxComponent
---@field PropsCollison01 UBoxComponent
---@field Decal1 UDecalComponent
---@field AITurretMarker01 UDecalComponent
---@field Cabinet6 UStaticMeshComponent
---@field AITurretMarker00 UDecalComponent
---@field window04 UStaticMeshComponent
---@field window01 UStaticMeshComponent
---@field PropsCollison04 UBoxComponent
---@field PropsCollison02 UBoxComponent
---@field Lamp02 UStaticMeshComponent
---@field Lamp01 UStaticMeshComponent
---@field StaticMesh30 UStaticMeshComponent
---@field StaticMesh26 UStaticMeshComponent
---@field StaticMesh24 UStaticMeshComponent
---@field StaticMesh22 UStaticMeshComponent
---@field StaticMesh18 UStaticMeshComponent
---@field StaticMesh16 UStaticMeshComponent
---@field Decal2 UDecalComponent
---@field StaticMesh13 UStaticMeshComponent
---@field StaticMesh6 UStaticMeshComponent
---@field StaticMesh3 UStaticMeshComponent
---@field Decal UDecalComponent
---@field StaticMesh1 UStaticMeshComponent
---@field StaticMeshProps UBoxComponent
---@field BPStructureInteriorArea UBPStructureInteriorArea_C
---@field BPAIGarrisonTurret3 UBPAIGarrisonTurret_C
---@field BPAIGarrisonTurret UBPAIGarrisonTurret_C
---@field ParticleSystem4 UParticleSystemComponent
---@field ParticleSystem1 UParticleSystemComponent
---@field MultiplexedRoof UMultiplexedStaticMeshComponent
---@field MultiplexedHouse UMultiplexedStaticMeshComponent
---@field Roof UStaticMeshComponent
---@field HouseMesh UStaticMeshComponent
local AVillageWMedAttachedG2_C = {}



